//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairCare.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LorealHairCareEntities : DbContext
    {
        public LorealHairCareEntities()
            : base("name=LorealHairCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AskExpert> AskExperts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ContentCategory> ContentCategories { get; set; }
        public virtual DbSet<ContentRelatedContent> ContentRelatedContents { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<FbNominee> FbNominees { get; set; }
        public virtual DbSet<IGPhoto> IGPhotos { get; set; }
        public virtual DbSet<IGUser> IGUsers { get; set; }
        public virtual DbSet<RelatedContent> RelatedContents { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<FBCombinedPhoto> FBCombinedPhotos { get; set; }
        public virtual DbSet<IGCombinedPhoto> IGCombinedPhotos { get; set; }
        public virtual DbSet<vwContentWithCategory> vwContentWithCategories { get; set; }
    
        public virtual ObjectResult<GetCategoryContentList_Result> GetCategoryContentList(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategoryContentList_Result>("GetCategoryContentList", categoryIdParameter);
        }
    
        public virtual ObjectResult<GetCombinedPhotoList_Result> GetCombinedPhotoList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCombinedPhotoList_Result>("GetCombinedPhotoList");
        }
    
        public virtual ObjectResult<GetContentDetail_Result> GetContentDetail(Nullable<int> contentId)
        {
            var contentIdParameter = contentId.HasValue ?
                new ObjectParameter("ContentId", contentId) :
                new ObjectParameter("ContentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetContentDetail_Result>("GetContentDetail", contentIdParameter);
        }
    
        public virtual ObjectResult<GetPopularContents_Result> GetPopularContents(Nullable<int> parentId)
        {
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("ParentId", parentId) :
                new ObjectParameter("ParentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPopularContents_Result>("GetPopularContents", parentIdParameter);
        }
    
        public virtual ObjectResult<GetRecentContents_Result> GetRecentContents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecentContents_Result>("GetRecentContents");
        }
    }
}
